name: Renovate

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:
  issues:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: get_token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ secrets.RENOVATE_APP_CLIENT_ID }}
          private-key: ${{ secrets.RENOVATE_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout
        uses: actions/checkout@v6
        with:
          token: ${{ steps.get_token.outputs.token }}

      - name: Cache Renovate
        uses: actions/cache@v5
        with:
          path: /tmp/renovate/cache
          key: renovate-cache-${{ runner.os }}

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v46.1.15
        with:
          configurationFile: renovate.config.js
          token: ${{ steps.get_token.outputs.token }}
